spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      # 分支
      label: master
      server:
        git:
          # git仓库地址
          uri: https://github.com/test/spring-cloud-config
          # 配置文件位置
          search-paths: respo
          # git账号密码
          username:
          password:

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/