spring:
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: root
    password: root
# 自定义属性
mq:
  config:
    exchange: log.direct
    # 队列信息
    queue:
      info:
        routing:
          key: log.info.routing.key
      error:
        routing:
          key: log.error.routing.key